name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set Secret
        env:
          MY_SECRET: ${{ secrets.REACT_APP_WEATHER_API_KEY }}
        run: echo "REACT_APP_WEATHER_API_KEY=${REACT_APP_WEATHER_API_KEY}" >> $GITHUB_ENV

      - name: Print Environment Variable
        run: echo "The value of REACT_APP_WEATHER_API_KEY is ${{ secrets.REACT_APP_WEATHER_API_KEY }}"

      - name: Clear Yarn cache
        run: yarn cache clean
                
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./build
